import { motion } from 'framer-motion';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui';

interface ConfidenceGaugeProps {
  confidence: number; // e.g. 97.4
}

export function ConfidenceGauge({ confidence }: ConfidenceGaugeProps) {
  // SVG Circle parameters
  const radius = 64;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (confidence / 100) * circumference;

  let badgeText = 'High Confidence';
  let badgeStyle = 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400';
  let strokeColor = '#22c55e';

  if (confidence < 70) {
    badgeText = 'Low Confidence';
    badgeStyle = 'bg-amber-500/10 border-amber-500/30 text-amber-400';
    strokeColor = '#f59e0b';
  } else if (confidence < 90) {
    badgeText = 'Medium Confidence';
    badgeStyle = 'bg-yellow-500/10 border-yellow-500/30 text-yellow-300';
    strokeColor = '#eab308';
  }

  return (
    <Card className="p-0 border border-white/10 overflow-hidden mb-6">
      <CardHeader className="p-6 pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-xl font-bold text-white flex items-center gap-2">
            <svg className="w-5 h-5 text-accent-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
            Certainty Rating
          </CardTitle>

          <span className={`px-3 py-1 rounded-full text-xs font-mono border font-semibold ${badgeStyle}`}>
            {badgeText}
          </span>
        </div>
        <CardDescription>Probabilistic certainty metric generated by AI model</CardDescription>
      </CardHeader>

      <CardContent className="p-6 flex flex-col sm:flex-row items-center justify-around gap-6">
        
        {/* SVG Gauge Ring */}
        <div className="relative w-44 h-44 flex items-center justify-center">
          <svg className="w-full h-full transform -rotate-90" viewBox="0 0 160 160">
            {/* Background Track */}
            <circle
              cx="80"
              cy="80"
              r={radius}
              stroke="rgba(255, 255, 255, 0.08)"
              strokeWidth="12"
              fill="transparent"
            />
            {/* Animated Gauge Arc */}
            <motion.circle
              cx="80"
              cy="80"
              r={radius}
              stroke={strokeColor}
              strokeWidth="12"
              strokeDasharray={circumference}
              initial={{ strokeDashoffset: circumference }}
              animate={{ strokeDashoffset }}
              transition={{ duration: 1.2, ease: 'easeOut' }}
              strokeLinecap="round"
              fill="transparent"
              style={{ filter: `drop-shadow(0 0 8px ${strokeColor}66)` }}
            />
          </svg>

          {/* Center Score Text */}
          <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
            <span className="text-3xl font-extrabold text-white font-mono tracking-tight">
              {confidence}%
            </span>
            <span className="text-[10px] text-slate-400 font-mono uppercase tracking-wider">
              Accuracy
            </span>
          </div>
        </div>

        {/* Confidence Tier Badges Legend */}
        <div className="space-y-3 w-full sm:w-auto">
          <div className="p-3 rounded-2xl glass border border-white/5 flex items-center justify-between gap-6 text-xs">
            <span className="flex items-center gap-2 text-slate-300">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 shadow-[0_0_8px_#22c55e]" />
              High Confidence (≥90%)
            </span>
            <span className="font-mono text-emerald-400 font-bold">Optimal</span>
          </div>

          <div className="p-3 rounded-2xl glass border border-white/5 flex items-center justify-between gap-6 text-xs">
            <span className="flex items-center gap-2 text-slate-300">
              <span className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
              Medium Confidence (70-89%)
            </span>
            <span className="font-mono text-yellow-400 font-bold">Acceptable</span>
          </div>

          <div className="p-3 rounded-2xl glass border border-white/5 flex items-center justify-between gap-6 text-xs">
            <span className="flex items-center gap-2 text-slate-300">
              <span className="w-2.5 h-2.5 rounded-full bg-red-400" />
              Low Confidence (&lt;70%)
            </span>
            <span className="font-mono text-red-400 font-bold">Retake Photo</span>
          </div>
        </div>

      </CardContent>
    </Card>
  );
}
