export { HeaderSection } from './HeaderSection';
export { ImageUploadCard } from './ImageUploadCard';
export { AnalysisProgress } from './AnalysisProgress';
export { PredictionResultCard, type PredictionData } from './PredictionResultCard';
export { ConfidenceGauge } from './ConfidenceGauge';
export { TreatmentCard, type TreatmentDetails } from './TreatmentCard';
export { PreventiveMeasures } from './PreventiveMeasures';
export { SimilarDiseases } from './SimilarDiseases';
export { PredictionTimeline } from './PredictionTimeline';
export { ExportActionsCard } from './ExportActionsCard';
export { ErrorCard } from './ErrorCard';
export { DetectionSkeleton } from './DetectionSkeleton';
